name: Deploy Sites

on:
  push:
    paths:
      - 'sites/**'
  workflow_dispatch:

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.collect.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Collect deployable sites
        id: collect
        run: |
          set -e
          if [ ! -d "sites" ]; then
            echo "matrix=[]" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          entries=""
          sep=""
          for dir in $(ls -1 sites); do
            if [ ! -d "sites/$dir" ]; then
              continue
            fi

            config="sites/$dir/site-config.json"
            if [ -f "$config" ]; then
              deploy=$(jq -r '.deploy // "true"' "$config")
              if [ "$deploy" = "true" ]; then
                entries="${entries}${sep}\"$dir\""
                sep=",";
              fi
            fi
          done

          echo "matrix=[${entries}]" >> "$GITHUB_OUTPUT"

  deploy:
    needs: discover
    if: ${{ needs.discover.outputs.matrix != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        site: ${{ fromJson(needs.discover.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare static assets
        id: prepare
        run: |
          set -e
          site="${{ matrix.site }}"
          source_dir="sites/${site}"
          publish_dir="dist/${site}"

          if [ ! -d "$source_dir" ]; then
            echo "Site directory $source_dir not found" >&2
            exit 1
          fi

          rm -rf "$publish_dir"
          mkdir -p "$publish_dir"
          cp -R "$source_dir"/. "$publish_dir"

          rm -rf "$publish_dir/docs"
          rm -f "$publish_dir/mcp-prompt.txt" "$publish_dir/site-config.json"

          echo "publish_dir=$publish_dir" >> "$GITHUB_OUTPUT"

      - name: Deploy (${{ matrix.site }})
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: dist
          skip_api_build: true
          azure_static_web_apps_api_token: ${{ secrets[ format('AZURE_STATIC_WEB_APPS_API_TOKEN_{0}', replace(toUpper(matrix.site), '-', '_')) ] }}
