name: Deploy Sites

on:
  push:
    paths:
      - 'sites/**'
  workflow_dispatch:

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.collect.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Collect deployable sites
        id: collect
        run: |
          set -e
          if [ ! -d "sites" ]; then
            echo "matrix=[]" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          arr="[]"
          # Monta lista de sites com deploy=true
          arr=$(jq -n '[]')
          for d in $(ls -1 sites); do
            cfg="sites/$d/site-config.json"
            [ -f "$cfg" ] || continue
            deploy=$(jq -r '.deploy // "true"' "$cfg")
            name=$(jq -r '.name // "'"$d"'"' "$cfg")
            [ "$deploy" = "true" ] || continue
            arr=$(echo "$arr" | jq --arg n "$name" '. + [$n]')
          done
          echo "Matriz final: $arr"
          echo "matrix=$arr" >> "$GITHUB_OUTPUT"

  deploy:
    needs: discover
    if: ${{ needs.discover.outputs.matrix != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        site: ${{ fromJson(needs.discover.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Derive secret name
        id: secret
        run: |
          RAW="${{ matrix.site }}"
          SANITIZED=$(echo "$RAW" | tr '[:lower:]' '[:upper:]' | tr '-' '_' )
            # Ex: workshop-ia -> WORKSHOP_IA
          echo "secret_name=AZURE_STATIC_WEB_APPS_API_TOKEN_${SANITIZED}" >> $GITHUB_OUTPUT
          echo "Using secret: AZURE_STATIC_WEB_APPS_API_TOKEN_${SANITIZED}"

      - name: Prepare publish dir
        id: prepare
        run: |
          PUBLISH="sites/${{ matrix.site }}"
          if [ ! -f "$PUBLISH/index.html" ]; then
            echo "Erro: index.html não encontrado em $PUBLISH" >&2
            exit 1
          fi
          echo "publish_dir=$PUBLISH" >> $GITHUB_OUTPUT

      - name: Deploy (${{ matrix.site }})
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: ${{ steps.prepare.outputs.publish_dir }}
          skip_api_build: true
          azure_static_web_apps_api_token: ${{ secrets[steps.secret.outputs.secret_name] }}
