name: Deploy Sites

on:
  push:
    paths:
      - 'sites/**'
  workflow_dispatch:

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.collect.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Collect deployable sites
        id: collect
        run: |
          set -e
          [ -d sites ] || { echo "matrix=[]" >> $GITHUB_OUTPUT; exit 0; }
          arr="[]"
          for d in $(ls -1 sites); do
            cfg="sites/$d/site-config.json"
            [ -f "$cfg" ] || continue
            deploy=$(jq -r '.deploy' "$cfg")
            name=$(jq -r '.name // "'"$d"'"' "$cfg")
            # Se deploy não for true, pula
            if [ "$deploy" != "true" ] && [ "$deploy" != "True" ] && [ "$deploy" != "TRUE" ]; then
              echo "Skip $name (deploy=false)"
              continue
            fi
            arr=$(echo "$arr" | jq --arg n "$name" '. + [$n]')
          done
          compact=$(echo "$arr" | jq -c '.')
          echo "matrix=$compact" >> $GITHUB_OUTPUT
          echo "Final matrix: $compact"

  deploy:
    needs: discover
    if: ${{ needs.discover.outputs.matrix != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        site: ${{ fromJson(needs.discover.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Derive secret name
        id: secret
        run: |
          RAW="${{ matrix.site }}"
          SANITIZED=$(echo "$RAW" | tr '[:lower:]' '[:upper:]' | tr '-' '_' )
          echo "secret_name=AZURE_STATIC_WEB_APPS_API_TOKEN_${SANITIZED}" >> $GITHUB_OUTPUT
          echo "Using secret: AZURE_STATIC_WEB_APPS_API_TOKEN_${SANITIZED}"

      - name: Prepare publish dir
        id: prepare
        run: |
          PUBLISH="sites/${{ matrix.site }}"
          [ -f "$PUBLISH/index.html" ] || { echo "index.html ausente em $PUBLISH" >&2; exit 1; }
          echo "publish_dir=$PUBLISH" >> $GITHUB_OUTPUT
          echo "Publish dir: $PUBLISH"

      - name: Deploy (${{ matrix.site }})
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: ${{ steps.prepare.outputs.publish_dir }}
          skip_api_build: true
          azure_static_web_apps_api_token: ${{ secrets[steps.secret.outputs.secret_name] }}
